### ISSUE TITLE
Grouping All Model Classes In Single Directory

### ISSUE THREAD

**Issue by robo220** [samthomson/rssme#1]
Would it be ok if we group all the model classes in a single directory? Perhaps in 'app/Models' or even directly in 'app'.

**Comment by samthomson** [comment]
Yup, will do soon, have a bunch of work to do on this, just need to schedule some time..

**Comment by robo220** [comment]
Is there anything I could do? I like the idea of this app.

**Comment by samthomson** [comment]
Maybe :)
I have quite a bit planned; some more key features, and then jazz up the UI, plus refactor the code - it's a mess, and not testable at all.
Will have a week off over Christmas where I'll maybe work on it. So for now I'd just say stay tuned and I'll ping you back when there's something to review and we can go from there.
